// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JImageFindResource_t.class, "apply", constants$1.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$1.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JIMAGE_GetResource",
        constants$2.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(JImageGetResource_t.class, "apply", constants$2.const$2);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$2.const$2
    );
}


