// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2 {

    static final FunctionDescriptor JIMAGE_GetResource$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS,
        JAVA_LONG,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle JIMAGE_GetResource$MH = RuntimeHelper.downcallHandle(
        "JIMAGE_GetResource",
        constants$2.JIMAGE_GetResource$FUNC, false
    );
    static final FunctionDescriptor JImageGetResource_t$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS,
        JAVA_LONG,
        ADDRESS,
        JAVA_LONG
    );
    static final MethodHandle JImageGetResource_t$MH = RuntimeHelper.downcallHandle(
        constants$2.JImageGetResource_t$FUNC, false
    );
    static final FunctionDescriptor JImageResourceVisitor_t$FUNC = FunctionDescriptor.of(JAVA_INT,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JImageResourceVisitor_t$MH = RuntimeHelper.downcallHandle(
        constants$2.JImageResourceVisitor_t$FUNC, false
    );
    static final FunctionDescriptor JIMAGE_ResourceIterator$FUNC = FunctionDescriptor.ofVoid(
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JIMAGE_ResourceIterator$MH = RuntimeHelper.downcallHandle(
        "JIMAGE_ResourceIterator",
        constants$2.JIMAGE_ResourceIterator$FUNC, false
    );
}


