// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1 {

    static final FunctionDescriptor JIMAGE_PackageToModule$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JIMAGE_PackageToModule$MH = RuntimeHelper.downcallHandle(
        "JIMAGE_PackageToModule",
        constants$1.JIMAGE_PackageToModule$FUNC, false
    );
    static final FunctionDescriptor JImagePackageToModule_t$FUNC = FunctionDescriptor.of(ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JImagePackageToModule_t$MH = RuntimeHelper.downcallHandle(
        constants$1.JImagePackageToModule_t$FUNC, false
    );
    static final FunctionDescriptor JIMAGE_FindResource$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JIMAGE_FindResource$MH = RuntimeHelper.downcallHandle(
        "JIMAGE_FindResource",
        constants$1.JIMAGE_FindResource$FUNC, false
    );
    static final FunctionDescriptor JImageFindResource_t$FUNC = FunctionDescriptor.of(JAVA_LONG,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS,
        ADDRESS
    );
    static final MethodHandle JImageFindResource_t$MH = RuntimeHelper.downcallHandle(
        constants$1.JImageFindResource_t$FUNC, false
    );
}


