// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JImageClose_t.class, "apply", constants$0.const$4);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$0.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JIMAGE_PackageToModule",
        constants$0.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JImagePackageToModule_t.class, "apply", constants$0.const$0);
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JIMAGE_FindResource",
        constants$1.const$4
    );
}


