// Generated by jextract

package org.openjdk;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef JImageFile *(*JImageOpen_t)(const char *, jint *)
 * }
 */
public class JImageOpen_t {

    public interface Function {
        MemorySegment apply(MemorySegment name, MemorySegment error);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER
    );

    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = jimage_h.upcallHandle(JImageOpen_t.Function.class, "apply", $DESC);

    public static MemorySegment allocate(JImageOpen_t.Function fi, Arena scope) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, scope);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment name, MemorySegment error) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, name, error);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

