// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class jimage_h  {

    public static final OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static final OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static final OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static final OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static final OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static final OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static final OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    /**
     * {@snippet :
     * #define JIMAGE_MAX_PATH 4096
     * }
     */
    public static int JIMAGE_MAX_PATH() {
        return (int)4096L;
    }
    /**
     * {@snippet :
     * typedef long long jlong;
     * }
     */
    public static final OfLong jlong = Constants$root.C_LONG_LONG$LAYOUT;
    /**
     * {@snippet :
     * typedef int jint;
     * }
     */
    public static final OfInt jint = Constants$root.C_INT$LAYOUT;
    /**
     * {@snippet :
     * typedef long long JImageLocationRef;
     * }
     */
    public static final OfLong JImageLocationRef = Constants$root.C_LONG_LONG$LAYOUT;
    public static MethodHandle JIMAGE_Open$MH() {
        return RuntimeHelper.requireNonNull(constants$0.JIMAGE_Open$MH,"JIMAGE_Open");
    }
    /**
     * {@snippet :
     * JImageFile* JIMAGE_Open(char* name, jint* error);
     * }
     */
    public static MemorySegment JIMAGE_Open(MemorySegment name, MemorySegment error) {
        var mh$ = JIMAGE_Open$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(name, error);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle JIMAGE_Close$MH() {
        return RuntimeHelper.requireNonNull(constants$0.JIMAGE_Close$MH,"JIMAGE_Close");
    }
    /**
     * {@snippet :
     * void JIMAGE_Close(JImageFile* jimage);
     * }
     */
    public static void JIMAGE_Close(MemorySegment jimage) {
        var mh$ = JIMAGE_Close$MH();
        try {
            mh$.invokeExact(jimage);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle JIMAGE_PackageToModule$MH() {
        return RuntimeHelper.requireNonNull(constants$1.JIMAGE_PackageToModule$MH,"JIMAGE_PackageToModule");
    }
    /**
     * {@snippet :
     * char* JIMAGE_PackageToModule(JImageFile* jimage, char* package_name);
     * }
     */
    public static MemorySegment JIMAGE_PackageToModule(MemorySegment jimage, MemorySegment package_name) {
        var mh$ = JIMAGE_PackageToModule$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(jimage, package_name);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle JIMAGE_FindResource$MH() {
        return RuntimeHelper.requireNonNull(constants$1.JIMAGE_FindResource$MH,"JIMAGE_FindResource");
    }
    /**
     * {@snippet :
     * JImageLocationRef JIMAGE_FindResource(JImageFile* jimage, char* module_name, char* version, char* name, jlong* size);
     * }
     */
    public static long JIMAGE_FindResource(MemorySegment jimage, MemorySegment module_name, MemorySegment version, MemorySegment name, MemorySegment size) {
        var mh$ = JIMAGE_FindResource$MH();
        try {
            return (long)mh$.invokeExact(jimage, module_name, version, name, size);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle JIMAGE_GetResource$MH() {
        return RuntimeHelper.requireNonNull(constants$2.JIMAGE_GetResource$MH,"JIMAGE_GetResource");
    }
    /**
     * {@snippet :
     * jlong JIMAGE_GetResource(JImageFile* jimage, JImageLocationRef location, char* buffer, jlong size);
     * }
     */
    public static long JIMAGE_GetResource(MemorySegment jimage, long location, MemorySegment buffer, long size) {
        var mh$ = JIMAGE_GetResource$MH();
        try {
            return (long)mh$.invokeExact(jimage, location, buffer, size);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle JIMAGE_ResourceIterator$MH() {
        return RuntimeHelper.requireNonNull(constants$2.JIMAGE_ResourceIterator$MH,"JIMAGE_ResourceIterator");
    }
    /**
     * {@snippet :
     * void JIMAGE_ResourceIterator(JImageFile* jimage, JImageResourceVisitor_t visitor, void* arg);
     * }
     */
    public static void JIMAGE_ResourceIterator(MemorySegment jimage, MemorySegment visitor, MemorySegment arg) {
        var mh$ = JIMAGE_ResourceIterator$MH();
        try {
            mh$.invokeExact(jimage, visitor, arg);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet :
     * #define JIMAGE_NOT_FOUND 0
     * }
     */
    public static int JIMAGE_NOT_FOUND() {
        return (int)0L;
    }
    /**
     * {@snippet :
     * #define JIMAGE_BAD_MAGIC -1
     * }
     */
    public static int JIMAGE_BAD_MAGIC() {
        return (int)-1L;
    }
    /**
     * {@snippet :
     * #define JIMAGE_BAD_VERSION -2
     * }
     */
    public static int JIMAGE_BAD_VERSION() {
        return (int)-2L;
    }
    /**
     * {@snippet :
     * #define JIMAGE_CORRUPTED -3
     * }
     */
    public static int JIMAGE_CORRUPTED() {
        return (int)-3L;
    }
}


