// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang=c :
 * typedef JImageFile *(*JImageOpen_t)(const char *, jint *)
 * }
 */
public interface JImageOpen_t {

    MemorySegment apply(MemorySegment name, MemorySegment error);

    FunctionDescriptor $DESC = FunctionDescriptor.of(
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER
    );

    MethodHandle UP$MH = jimage_h.upcallHandle(JImageOpen_t.class, "apply", $DESC);

    static MemorySegment allocate(JImageOpen_t fi, Arena scope) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, scope);
    }

    MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    static JImageOpen_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _name, MemorySegment _error) -> {
            try {
                return (MemorySegment) DOWN$MH.invokeExact(symbol, _name, _error);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}

