// Generated by jextract

package org.openjdk;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * JImageResourceVisitor_t visitor
 * }
 */
public class JIMAGE_ResourceIterator$visitor {

    public interface Function {
        int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        jimage_h.C_INT,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER
    );

    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = jimage_h.upcallHandle(JIMAGE_ResourceIterator$visitor.Function.class, "apply", $DESC);

    public static MemorySegment allocate(JIMAGE_ResourceIterator$visitor.Function fi, Arena scope) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, scope);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, MemorySegment _x4, MemorySegment _x5, MemorySegment _x6) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5, _x6);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

