// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet lang=c :
 * typedef void (*JImageClose_t)(JImageFile *)
 * }
 */
public interface JImageClose_t {

    void apply(MemorySegment jimage);

    FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        jimage_h.C_POINTER
    );

    MethodHandle UP$MH = jimage_h.upcallHandle(JImageClose_t.class, "apply", $DESC);

    static MemorySegment allocate(JImageClose_t fi, Arena scope) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, scope);
    }

    MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    static JImageClose_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (MemorySegment _jimage) -> {
            try {
                 DOWN$MH.invokeExact(symbol, _jimage);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}

