// Generated by jextract

package org.openjdk;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface JImageClose_t {

    void apply(java.lang.foreign.MemoryAddress jimage);
    static MemorySegment allocate(JImageClose_t fi, MemorySession scope) {
        return RuntimeHelper.upcallStub(JImageClose_t.class, fi, constants$0.JImageClose_t$FUNC, "(Ljava/lang/foreign/MemoryAddress;)V", scope);
    }
    static JImageClose_t ofAddress(MemoryAddress addr, MemorySession scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, scope);
        return (java.lang.foreign.MemoryAddress _jimage) -> {
            try {
                constants$0.JImageClose_t$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_jimage);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


