// Generated by jextract

package org.openjdk;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef JImageLocationRef (*JImageFindResource_t)(JImageFile *, const char *, const char *, const char *, jlong *)
 * }
 */
public class JImageFindResource_t {

    public interface Function {
        long apply(MemorySegment jimage, MemorySegment module_name, MemorySegment version, MemorySegment name, MemorySegment size);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        jimage_h.C_LONG_LONG,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER,
        jimage_h.C_POINTER
    );

    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = jimage_h.upcallHandle(JImageFindResource_t.Function.class, "apply", $DESC);

    public static MemorySegment allocate(JImageFindResource_t.Function fi, Arena scope) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, scope);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    public static long invoke(MemorySegment funcPtr,MemorySegment jimage, MemorySegment module_name, MemorySegment version, MemorySegment name, MemorySegment size) {
        try {
            return (long) DOWN$MH.invokeExact(funcPtr, jimage, module_name, version, name, size);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

