/*
 *  Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This code is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 only, as
 *  published by the Free Software Foundation.  Oracle designates this
 *  particular file as subject to the "Classpath" exception as provided
 *  by Oracle in the LICENSE file that accompanied this code.
 *
 *  This code is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 *  version 2 for more details (a copy is included in the LICENSE file that
 *  accompanied this code).
 *
 *  You should have received a copy of the GNU General Public License version
 *  2 along with this work; if not, write to the Free Software Foundation,
 *  Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 *   Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 *  or visit www.oracle.com if you need additional information or have any
 *  questions.
 */

// Generated by jextract

package org.openjdk.jextract.clang.libclang;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct CXUnsavedFile {
 *     const char *Filename;
 *     const char *Contents;
 *     unsigned long Length;
 * }
 * }
 */
public class CXUnsavedFile {

    CXUnsavedFile() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Index_h.C_POINTER.withName("Filename"),
        Index_h.C_POINTER.withName("Contents"),
        Index_h.C_LONG.withName("Length")
    ).withName("CXUnsavedFile");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout Filename$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Filename"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static final AddressLayout Filename$layout() {
        return Filename$LAYOUT;
    }

    private static final long Filename$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static final long Filename$offset() {
        return Filename$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static MemorySegment Filename(MemorySegment struct) {
        return struct.get(Filename$LAYOUT, Filename$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *Filename
     * }
     */
    public static void Filename(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Filename$LAYOUT, Filename$OFFSET, fieldValue);
    }

    private static final AddressLayout Contents$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("Contents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static final AddressLayout Contents$layout() {
        return Contents$LAYOUT;
    }

    private static final long Contents$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static final long Contents$offset() {
        return Contents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static MemorySegment Contents(MemorySegment struct) {
        return struct.get(Contents$LAYOUT, Contents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *Contents
     * }
     */
    public static void Contents(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(Contents$LAYOUT, Contents$OFFSET, fieldValue);
    }

    private static final OfLong Length$LAYOUT = (OfLong)$LAYOUT.select(groupElement("Length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static final OfLong Length$layout() {
        return Length$LAYOUT;
    }

    private static final long Length$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static final long Length$offset() {
        return Length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static long Length(MemorySegment struct) {
        return struct.get(Length$LAYOUT, Length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned long Length
     * }
     */
    public static void Length(MemorySegment struct, long fieldValue) {
        struct.set(Length$LAYOUT, Length$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

